---

name: "Infra setup for Production"

on:
  push:
    branches:
      - production

  repository_dispatch:
    types: [prod-ami-deploy-event]

jobs:

  build: 
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
      AWS_REGION: ${{ secrets.PROD_REGION }}

    steps: 

      - name: "Repository Chcekout"
        uses: actions/checkout@v3

      - name: "Terraform Installation"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: "Initializing Terraform"
        run: |
          terraform init \
            --backend-config="bucket=${{ secrets.PROD_S3_BUCKET  }}" \
            --backend-config="key=terraform.tfstate" \
            --backend-config="access_key=${{ secrets.PROD_ACCESS_KEY }}" \
            --backend-config="secret_key=${{ secrets.PROD_SECRET_KEY }}" \
            --backend-config="region=${{ secrets.PROD_REGION }}" \

      - name: "Formatting Terraform files"
        run: terraform fmt

      - name: "Validating Terraform files"
        run: terraform validate

      - name: "Terraform Plan"
        run: terraform plan -var-file=production.tfvars

      - name: "Terraform Apply"
        run: terraform apply -auto-approve -var-file=production.tfvars
          
